Hf = tf(2, [50 15 1], 'IOdelay', 3);
gammakStar = 50;
argHol = -180 + gammakStar;
argHf = -180 + 15 + gammakStar;
figure;
subplot(1,2,1);
bode(Hf); title('Hf');
subplot(1,2,2);
step(Hf); title('Hf');
wc = 0.136;
Ti = 4/wc;
N = -0.58;
M = 10^(N/20);
kp = 1/M;
Hol = kp*tf([Ti 1], [Ti 0])*Hf;
gammakstar = 50;
beta = 0.1;
argHc = rad2deg(atan((1-beta)/(2*sqrt(beta))));
argHf = -180 -argHc + gammakstar;
wc = 0.318;
td = 1/wc/sqrt(beta);
N = -9.9;
M = 10^(N/20);
kp = sqrt(beta)/M;
Hc = kp*tf([td 1], [beta*td 1])*Hf;
figure;
subplot(1,2,1);
hold on;
bode(Hol);
bode(Hc);
hold off;
subplot(1,2,2);
hold on;
step(feedback(Hol,1));
step(feedback(Hc,1));
hold off;
legend('PI','PD');